name: login EC2
on:
  push:
    branches:
      - main
      - feature/*
jobs:

  build:
    name: login EC2
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-94-110-140.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu"