name: remote ssh command
on:
  push:
    branches:
      - main
      - feature/*
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Login to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }}
        username: ubuntu
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Successfully logged in to EC2 instance."